id: IE5F9533F
legacy_id: P006861
ocr_import_info:
  bdrc_scan_id: W2GS1315
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:51:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T17:42:00.322539+00:00'
last_modified: 2022-09-03 01:42:11.344092
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2GS1315
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2GS1315
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཁྲི་ཆེན་བློ་བཟང་དགེ་ལེགས་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་དད་པའི་པད་མོའི་འཛུམ་བྱེད་ངོ་མཚར་ཉིན་བྱེད་གསར་པའི་སྣང་བ།
  author: ཚེ་སྨོན་གླིང ༠༡་ངག་དབང་ཚུལ་ཁྲིམས།
statistics:
  ocr_word_mean_confidence_index: 0.47296373789475366
  ocr_word_median_confidence_index: 0.4099999964237213
quality: null
bases:
  I1KG6104:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG6104
      total_pages: 40
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG6104.txt
    statistics:
      ocr_word_median_confidence_index: 0.4099999964237213
      ocr_word_mean_confidence_index: 0.47296373789475366
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
